site_name: Guía Morphman
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: green
  language: es
  features:
    - header.autohide
    - navigation.indexes
    - navigation.sections
plugins:
  - search
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html

nav:
  - Inicio: index.md
  - Definiciones: 
    - ¿Qué es morphman?: definiciones/queesmorphman.md
    - Términos usados: definiciones/palabrasmorphman.md
  - Puesta a punto: 
    - Instalación: preparar/instalar.md
    - Añadiendo decks prefabricados: preparar/newdecks.md
    - Configuración:
      - Morphman: preparar/configurar_morhpman.md
      - Lecturas: preparar/configurar_lecturas.md
      - Definiciones: preparar/configurar_definiciones.md
    - Selección de cartas: preparar/consejos.md
  - Uso: 
    - Crear decks de anime: uso/crear.md
    - Rutina de morphman: uso/rutina.md
extra_css:
  - stylesheets/extra.css